-- 코드를 입력하세요
SELECT A.AUTHOR_ID as AUTHOR_ID , A.AUTHOR_NAME as AUTHOR_NAME,  B.CATEGORY as CATEGORY ,SUM(SALES * PRICE) as TOTAL_SALES
FROM BOOK B JOIN BOOK_SALES BS ON B.BOOK_ID = BS.BOOK_ID 
JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE DATE_FORMAT(BS.SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY A.AUTHOR_ID,  B.CATEGORY
ORDER BY A.AUTHOR_ID, B.CATEGORY desc