-- 코드를 입력하세요
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, sum(B.PRICE * SALES) AS TOTAL_SALES
FROM BOOK B JOIN BOOK_SALES BK ON B.BOOK_ID = BK.BOOK_ID
JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY A.AUTHOR_ID, B.CATEGORY
Order BY A.AUTHOR_ID, B.CATEGORY desc