-- 코드를 입력하세요
SELECT R.REST_ID, R.REST_NAME, R.FOOD_TYPE, R.FAVORITES, R.ADDRESS, ROUND(AVG(RR.REVIEW_SCORE),2) as SCORE
FROM REST_INFO R JOIN REST_REVIEW RR ON R.REST_ID = RR.REST_ID
WHERE  R.ADDRESS LIKE '서울%'
GROUP BY R.REST_NAME
ORDER BY SCORE desc ,R.FAVORITES  desc