-- 코드를 입력하세요
SELECT CAR_ID, ROUND(AVG(DATEDIFF(END_DATE
, START_DATE) + 1),1) as AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
Group By CAR_ID
Having AVERAGE_DURATION >= 7
Order By AVERAGE_DURATION desc ,CAR_ID desc