SELECT
    ROUTE,
    CONCAT(ROUND(SUM(D_BETWEEN_DIST),1),'km') as TOTAL_DISTANCE,
    CONCAT(ROUND(avg(D_BETWEEN_DIST),2),'km') as AVERAGE_DISTANCE

FROM SUBWAY_DISTANCE
Group By ROUTE
Order By SUM(D_BETWEEN_DIST) desc