-- 코드를 입력하세요
SELECT f.PRODUCT_ID, f.PRODUCT_NAME, SUM(o.AMOUNT * f.PRICE) as TOTAL_SALES
FROM FOOD_PRODUCT f JOIN FOOD_ORDER o ON f.PRODUCT_ID = o.PRODUCT_ID
WHERE o.PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31' 
GROUP BY f.PRODUCT_ID
ORDER BY TOTAL_SALES desc, f.PRODUCT_ID 