-- 코드를 입력하세요
SELECT USER_ID, NICKNAME, sum(price) as TOTAL_SALES
FROM USED_GOODS_BOARD S JOIN USED_GOODS_USER U ON S.WRITER_ID = U.USER_ID
WHERE STATUS = 'DONE'
GROUP BY S.WRITER_ID
HAVING TOTAL_SALES >= 700000
Order By TOTAL_SALES
