-- 코드를 입력하세요
SELECT u.USER_ID, u.NICKNAME, SUM(us.PRICE) as TOTAL_SALES
FROM USED_GOODS_USER u
JOIN USED_GOODS_BOARD us ON u.USER_ID = us.WRITER_ID
WHERE us.STATUS = 'DONE'
GROUP BY u.USER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES 
