SELECT U.ITEM_ID, U.ITEM_NAME, U.RARITY
FROM ITEM_TREE T
JOIN ITEM_INFO P ON T.PARENT_ITEM_ID = P.ITEM_ID  -- 부모 아이템이 'RARE'인지 확인
JOIN ITEM_INFO U ON T.ITEM_ID = U.ITEM_ID  -- 업그레이드된 아이템 정보 가져오기
WHERE P.RARITY = 'RARE'  -- 부모 아이템이 'RARE'인 경우만 선택
ORDER BY U.ITEM_ID DESC;