-- 코드를 입력하세요
SELECT CONCAT('/home/grep/src/', U.BOARD_ID, '/', FILE_ID, FILE_NAME, FILE_EXT) AS FILE_PATH
FROM USED_GOODS_BOARD U JOIN USED_GOODS_FILE F ON U.BOARD_ID = F.BOARD_ID
WHERE U.VIEWS IN (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
ORDER BY 1 desc