-- 코드를 입력하세요
SELECT b.CATEGORY, SUM(bs.SALES) as TOTAL_SALES
FROM BOOK b
JOIN BOOK_SALES bs ON b.book_id = bs.book_id
WHERE bs.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY CATEGORY
ORDER BY b.CATEGORY