-- 코드를 입력하세요
SELECT CATEGORY	, SUM(SALES) as SALES_DATE
FROM BOOK B JOIN BOOK_SALES BS ON B.BOOK_ID = BS.BOOK_ID
WHERE bs.SALES_DATE >= '2022-01-01'
  AND bs.SALES_DATE < '2022-02-01'
GROUP BY CATEGORY	
ORDER BY CATEGORY