SELECT count(*) as FISH_COUNT, MAX(LENGTH) as MAX_LENGTH, FISH_TYPE
FROM FISH_INFO 
WHERE FISH_TYPE IN ( SELECT FISH_TYPE FROM FISH_INFO GROUP BY FISH_TYPE HAVING  AVG(LENGTH) >= 33)
GROUP BY FISH_TYPE
Order By FISH_TYPE